### ISSUE TITLE
Proper releases

### ISSUE THREAD

**Issue by davelab6** [huertatipografica/Alegreya#10]
https://github.com/huertatipografica/Alegreya/releases has tags, but not "proper" releases - its another option on the Github page there, and allows you to attach a ZIP to each "proper release" - that you craft yourself, with "just" the fonts + license + readme :) 

In https://github.com/JulietaUla/Montserrat/releases you did it a 'proper' release, but didn't include a crafted ZIP. Would be good to do for Alegreya, Alegreya Sans and newtella, I mean, Montserrat v7

**Comment by davelab6** [comment]
Ping

**Comment by juandelperal** [comment]
OK, we will add them

2017-11-14 17:53 GMT-03:00 Dave Crossland <notifications@github.com>:
