### ISSUE TITLE
Mangled or missing 'A' in PDF output

### ISSUE THREAD

**Issue by mdekstrand** [huertatipografica/Alegreya#15]
I greatly enjoy the Alegreya font - thank you!

I am observing a problem with the Roman 'A' glyph when embedding the font in PDF files. Under Firefox's PDF.js viewer and Edge's PDF viewer, the 'A' is missing; in Chrome's PDF viewer, it is mangled.

This problem can be observed in the following PDFs of my CV that I am setting in Alegreya. See the Ph.D line; should be 'Advisers' and 'Joseph A. Konstan'. The italic does not seem to have a problem.

- [Generated from HTML with WeasyPrint](https://md.ekstrandom.net/cv-short.pdf)
- [Generated from HTML with Chrome Print to PDF](https://github.com/huertatipografica/Alegreya/files/2205978/Michael.D.Ekstrand.CV.pdf)

Both of these are generated from the HTML documents at https://md.ekstrandom.net/cv.

**Comment by mdekstrand** [comment]
This only seems to be a problem when using the OpenType font file. Using the WOFF2 files is fine.

I use the OpenType files for printing because WeasyPrint does not support WOFF.

**Comment by juandelperal** [comment]
Thank you very much Michael! 
Did you try the ttf fonts?

**Comment by mdekstrand** [comment]
Yes, TrueType does seem to fix it.

**Comment by juandelperal** [comment]
Thanks @mdekstrand
