### ISSUE TITLE
Weight Axis variable font

### ISSUE THREAD

**Issue by pichotta** [huertatipografica/Alegreya#23]
@juandelperal

Hello Juan Pablo,

As mentioned in my recent email the Google fonts team would love to see a variable fonts version of ‘Alegreya'. They have commissioned us @TypeNetwork to work on upgrading a number of font projects to be variable fonts with a single weight axis.

In order to achieve the highest quality and most efficient long term results, we will be converting the source data from Glyphs to UFO. The new source data will be generated in the RoboFont environment using fontmake and ttfautohint. There has been recent progress on tools to make an easy path to move between the Glyphs and Robofont environment.

During the process, we will be looking to improve any errors while preserving how the font appears and renders on different platforms.

We have started by making a fork off of this git repository. The upgrade will be completed for you in the near future. When the proposed final font is approved by Google will you accept a pull request?

To confirm, are the .glyphs source files on this git repository from Aug 8, 2018 the most current data? 
	Alegreya italic.glyphs	
	Alegreya.glyphs  

We hope this answers some of your questions about the process. Please let us know if you have any additional comments.

Best Regards,

Jill Pichotta
Vice President
Type Network
pichotta@typenetwork.com

**Comment by pichotta** [comment]
–fixed incompatible glyphs
–added a build.sh script
–went through the errors in fontbakery.
–the diffenator is showing mostly improvements.

**Comment by juandelperal** [comment]
Hi Jill,
Sorry for the delay.
Yes. I can confirm that these repositories contain the latests versions of both Alegreyas. 
Go ahead  :)
Thanks for your help. Of course we will accept the PR. 
Are you using fontmake? I would ask you if you can document the converting/building flow, so we can keep working on further improvements while  keeping the changes you are working on. 
Thanks

**Comment by pichotta** [comment]
The build uses gftools and Bash in Terminal.
bash build.sh

gftools --help
ufo2glyphs --help
glyphs2ufo --help
