### ISSUE TITLE
Cyrillic review in Italic

### ISSUE THREAD

**Issue by alexeiva** [huertatipografica/Alegreya#3]
- [x] `л` `м`

<img width="1081" alt="screen shot 2016-11-24 at 6 09 08 pm" src="https://cloud.githubusercontent.com/assets/16634089/20607300/585bf08a-b277-11e6-92be-028c32ec20dd.png">

- [x] `ь` `ъ`

<img width="665" alt="screen shot 2016-11-24 at 6 09 18 pm" src="https://cloud.githubusercontent.com/assets/16634089/20607304/5d7eef9a-b277-11e6-948e-32a9d779a1e0.png">

- [x] `brevecomb-cy`

<img width="1239" alt="screen shot 2016-11-24 at 6 18 30 pm" src="https://cloud.githubusercontent.com/assets/16634089/20607310/682b98c6-b277-11e6-8d68-d688b6a922e8.png">

- [ ] `з` lacks a bottom terminal. Match with `э`
<img width="770" alt="screen shot 2016-11-24 at 6 43 34 pm" src="https://cloud.githubusercontent.com/assets/16634089/20607312/727be48e-b277-11e6-839c-4c4db6679561.png">

- [x] `ф` should more similar to bowls form `d`+`p` 
<img width="811" alt="screen shot 2016-11-24 at 6 43 38 pm" src="https://cloud.githubusercontent.com/assets/16634089/20607315/778c911c-b277-11e6-9586-798f1af99890.png">

- [x] `б`
<img width="965" alt="screen shot 2016-11-24 at 6 52 35 pm" src="https://cloud.githubusercontent.com/assets/16634089/20607316/7dbc513a-b277-11e6-9ac8-c3b58bf4d2b0.png">

**Comment by juandelperal** [comment]
Thanks!

**Comment by juandelperal** [comment]
Hi Alexei, I made those changes. Do you think it's time to start the Cyr plus character set or we have to improve the design before going there? Thanks

**Comment by alexeiva** [comment]
@juandelperal go ahead with CYR Plus. I will check your update. 

For Cyr Plus you can use my [GlyphsData](https://github.com/alexeiva/alexei-glyphs-scripts/tree/master/GlyphsData). Drop it in the same folder as your Glyphs file and it will auto-generate a most of the components once you have got
`descender-cy` `descender-cy.case` `strokeshortcomb`

**Comment by alexeiva** [comment]
**ж** the new form is great
<img width="342" alt="screen shot 2016-11-28 at 5 58 04 pm" src="https://cloud.githubusercontent.com/assets/16634089/20679912/2164080a-b59d-11e6-9d12-c84911f9d4bb.png">

**к**
Would be good to have an upward flick in the bottom limb. The current form feels too Greek (kappa), and this abrupt movement isn't supported in other glyphs. 

<img width="1180" alt="screen shot 2016-11-28 at 6 57 22 pm" src="https://cloud.githubusercontent.com/assets/16634089/20679751/83d23c10-b59c-11e6-9c23-f29640ab9d7b.png">

**У** — diagonal is too dark
<img width="444" alt="screen shot 2016-11-28 at 6 00 42 pm" src="https://cloud.githubusercontent.com/assets/16634089/20679830/c6b87ce2-b59c-11e6-91ae-c9f632f6857d.png">


**Й** Cyrillic kratka (breve). Uppercase forms require a wider kratka 
<img width="380" alt="screen shot 2016-11-28 at 6 22 33 pm" src="https://cloud.githubusercontent.com/assets/16634089/20679856/e64548b0-b59c-11e6-90ed-519c4768ed07.png">

I have added a `brevecomb-cy.case` for Italic:
<img width="455" alt="screen shot 2016-11-28 at 7 03 06 pm" src="https://cloud.githubusercontent.com/assets/16634089/20679946/4c4844b4-b59d-11e6-8a0c-95e2fffb100f.png">


The Bold **Ф** is too light in both Italic and Roman styles. The sides of the bowls should be thicker. 
<img width="875" alt="screen shot 2016-11-28 at 5 59 40 pm" src="https://cloud.githubusercontent.com/assets/16634089/20679965/5dea0cde-b59d-11e6-9489-656b78aab917.png">

<img width="697" alt="screen shot 2016-11-28 at 6 23 25 pm" src="https://cloud.githubusercontent.com/assets/16634089/20679968/62433b70-b59d-11e6-9df8-b302fa8f5f50.png">

I suggest raising the stem above the CAP height to create more space for the bowls. 
References:
<img width="423" alt="screen shot 2016-11-28 at 7 04 37 pm" src="https://cloud.githubusercontent.com/assets/16634089/20680014/87ac4fd2-b59d-11e6-90b4-e635829c1bc3.png">

г д я 
**г** is too wide, and the middle angle can be sharper
**я** adjust the angle of the bowl an seen on the image
**д** the ascender isn't right yet. It is too long. 

<img width="736" alt="screen shot 2016-11-28 at 7 12 19 pm" src="https://cloud.githubusercontent.com/assets/16634089/20680287/ac6f72e4-b59e-11e6-9b98-781118d03a11.png">
