### ISSUE TITLE
+smcp does not convert f* ligatures

### ISSUE THREAD

**Issue by RGB-es** [huertatipografica/Alegreya#6]
Testing 2.0 RC1 I've found a problem with the +smcp feature: the f ligatures (fi, fl, ft, etc) does not change

![alegreya-smcp-fi](https://user-images.githubusercontent.com/7756783/27685007-af3696b2-5ccc-11e7-8b82-25716b514ab4.png)

I need to use +smcp&-liga to get the right result.

**Comment by juandelperal** [comment]
Thank you very much @RGB-es for pointing this. Now fixed

**Comment by RGB-es** [comment]
Thanks to you! That was fast! You are amazing!

2017-06-29 18:25 GMT+02:00 Juan del Peral <notifications@github.com>:
